# set prefix
unbind C-b
set -g prefix C-Space
bind C-space send-prefix

# Shift alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'erikw/tmux-dark-notify'

# colors
set -g default-terminal "tmux-256color"
set -g terminal-overrides ",xterm-256color:RGB"
# set-option -ga terminal-overrides ",screen-256color:RGB"

# Theme
set -g @dark-notify-theme-path-light '$HOME/.config/tmux/plugins/theme/light.conf'
set -g @dark-notify-theme-path-dark '$HOME/.config/tmux/plugins/theme/dark.conf'

# set -g @catppuccin_flavor 'latte'

# set -g @catppuccin_reset "true"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# set -g @catppuccin_flavor 'latte'
# set -g @catppuccin_status_background 'none'
# set -g @catppuccin_status_fill "icon"
# set -g @catppuccin_status_module_bg_color "#{@thm_surface_0}"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Ensure that everything on the right side of the status line
# is included.
set -g status-right-length 100

# Start windows at index 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# mouse support 
set -g mouse on

set -g default-command /opt/homebrew/bin/fish
set -g default-shell /opt/homebrew/bin/fish

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
