[theme]
name = "catppuccin-latte"
auto_switch = true
dark_name = "catppuccin"
light_name = "catppuccin-latte"

[keys]
prefix = "ctrl+space"
settings = "prefix+comma"
goto = "prefix+s"
split_vertical = "prefix+%"
split_horizontal = "prefix+\""
focus_pane_left = "ctrl+h"
focus_pane_up = "ctrl+k"
focus_pane_down = "ctrl+j"
focus_pane_right = "ctrl+l"
